# Generated by Django 4.2.1 on 2023-05-30 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auto',
        ),
        migrations.DeleteModel(
            name='marque',
        ),
    ]
