# Generated by Django 4.2.1 on 2023-05-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='pays',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
